pipeline:

  install:
    image: node:8.6.0
    commands:
      - node -v
      - npm i

  scp:
    image: appleboy/drone-scp
    settings:
      host: 7.ndo.dev
      port: 2424  
      username: ndo
      key: 
        from_secret: DEPLOY_PRIVATE_KEY
      target: /var/www/html/landing-syzygy-prod/
      source:
        - "*.js"
        - pm2.json
        - node_modules
        - assets
#    when:
#      branch: master


