kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  secrets:
    - ENV 
  commands:
    - node -v
    - npm i
    - cat $${ENV} > .env

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: DEPLOY_HOST_IP
    port:   
      from_secret: DEPLOY_HOST_PORT
    username: ndo
    key: 
      from_secret: DEPLOY_PRIVATE_KEY
    rm: true
    target: /var/www/html/ndo-nt-landing
    source:
      - /drone/src/*
    strip_components: 2

- name: reload pm2
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: DEPLOY_HOST_IP
    port:   
      from_secret: DEPLOY_HOST_PORT
    username: ndo
    key: 
      from_secret: DEPLOY_PRIVATE_KEY
    command_timeout: 2m
    script:
      - cp /var/www/html/landing-syzygy-prod/.env /var/www/html/ndo-nt-landing/.env
      - pm2 restart 4
