kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  commands:
    - node -v
    - npm i

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: DEPLOY_HOST_IP
    port:   
      from_secret: DEPLOY_HOST_PORT
    username: ndo
    key: 
      from_secret: DEPLOY_PRIVATE_KEY
    target: /var/www/html/ndo-nt-landing
    source:
      - "*.js"
      - index.html
      - pm2.json
      - node_modules
      - assets
