pipeline:

  install:
    image: node:8.6.0
    commands:
      - node -v
      - npm i

  scp:
    image: appleboy/drone-scp
    settings:
      host: $DEPLOY_HOST_IP
      port: $DEPLOY_HOST_PORT
      username: ndo
      key: $DEPLOY_PRIVATE_KEY
      target: /var/www/html/landing-syzygy-prod/
      source:
        - "*.js"
        - pm2.json
        - node_modules
        - assets
#    when:
#      branch: master


