kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  secrets:
    - ENV 
  commands:
    - node -v
    - npm i
    - cat $ENV > .env

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 
      from_secret: DEPLOY_HOST_IP
    port:   
      from_secret: DEPLOY_HOST_PORT
    username: ndo
    key: 
      from_secret: DEPLOY_PRIVATE_KEY
    rm: true
    target: /var/www/html/ndo-nt-landing
    source:
      - "/drone/src/*"
